spring:
  application:
    name: hello-spring
  # 데이터 베이스 연결을 위한 설정
  datasource:  
    url: jdbc:oracle:thin:@localhost:1521:XE
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: SPRING_BOOT
    password: 1234
  #jsp를 사용하기 위해 jsp 파일들의 경로를 설정
# webConfig.java로 설정 이동
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp
  servlet:
    multipart:
      #애플리케이션이 받을 수 있는 최대 업로드 용량(바이트 단위)
      max-file-size: 104857600
      
      max-request-size: 10485760
        
#mybatis 설정 파일의 경로 지정
mybatis:
#mybatis-config.xml 파일의 위치를 지정
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:com/ktdsuniversity/edu/hello_spring/**/dao/mapper/*Mapper.xml


# apllication 전용 설정. (Spring과 관계 없음)

app:
  multipart:
    base-dir: C:\\uploadfiles
    obfuscation:
      enable: true
      hide-ext:
        enable: true








